/* JS */ gapi.loaded_1(function(_){var window=this;
var og;_.ng=function(a){return a[_.Ia]||(a[_.Ia]=++og)};_.pg=function(a){var b=typeof a;return"object"==b&&a!=_.p||"function"==b};_.qg=function(a){return"function"==(0,_.ma)(a)};_.rg=function(a){return"number"==typeof a};_.sg=function(){};_.tg=function(a,b,c){t:{for(var d=a.length,f=(0,_.xa)(a)?a.split(""):a,g=0;g<d;g++)if(g in f&&b.call(c,f[g],g,a)){b=g;break t}b=-1}return 0>b?_.p:(0,_.xa)(a)?a.charAt(b):a[b]};_.ug=function(a,b){return 0<=(0,_.vg)(a,b)};
_.wg=function(a,b){var c=(0,_.vg)(a,b),d;(d=0<=c)&&_.xg.splice.call(a,c,1);return d};_.yg=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};_.zg=function(a,b,c){return 2>=arguments.length?_.xg.slice.call(a,b):_.xg.slice.call(a,b,c)};og=0;_.xg=Array.prototype;
_.vg=_.xg.indexOf?function(a,b,c){return _.xg.indexOf.call(a,b,c)}:function(a,b,c){c=c==_.p?0:0>c?Math.max(0,a.length+c):c;if((0,_.xa)(a))return(0,_.xa)(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};_.Ag=_.xg.forEach?function(a,b,c){_.xg.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=(0,_.xa)(a)?a.split(""):a,g=0;g<d;g++)g in f&&b.call(c,f[g],g,a)};
_.Bg=_.xg.filter?function(a,b,c){return _.xg.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=[],g=0,h=(0,_.xa)(a)?a.split(""):a,m=0;m<d;m++)if(m in h){var q=h[m];b.call(c,q,m,a)&&(f[g++]=q)}return f};_.Cg=_.xg.map?function(a,b,c){return _.xg.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=Array(d),g=(0,_.xa)(a)?a.split(""):a,h=0;h<d;h++)h in g&&(f[h]=b.call(c,g[h],h,a));return f};
_.Dg=_.xg.some?function(a,b,c){return _.xg.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=(0,_.xa)(a)?a.split(""):a,g=0;g<d;g++)if(g in f&&b.call(c,f[g],g,a))return _.n;return _.t};_.Eg=_.xg.every?function(a,b,c){return _.xg.every.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=(0,_.xa)(a)?a.split(""):a,g=0;g<d;g++)if(g in f&&!b.call(c,f[g],g,a))return _.t;return _.n};

_.qi=function(){};_.ri=function(a,b){var c=(0,_.Ea)(_.si,b);a.fa||(a.fa=[]);a.fa.push((0,_.H)(c,_.l))};_.si=function(a){a&&"function"==typeof a.ha&&a.ha()};_.qi.prototype.ne=_.t;_.qi.prototype.gb=(0,_.u)("ne");_.qi.prototype.ha=function(){this.ne||(this.ne=_.n,this.U())};_.qi.prototype.U=function(){if(this.fa)for(;this.fa.length;)this.fa.shift()()};
_.ti=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)};_.ui=function(a){var b=0,c;for(c in a)b++;return b};_.vi=function(a,b){for(var c in a)if(a[c]==b)return _.n;return _.t};_.wi=function(a){for(var b in a)return _.t;return _.n};_.xi=function(a){var b={},c;for(c in a)b[c]=a[c];return b};_.yi=function(a,b){for(var c,d,f=1;f<arguments.length;f++){d=arguments[f];for(c in d)a[c]=d[c];for(var g=0;g<zi.length;g++)c=zi[g],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};var zi="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");

_.Ai=function(a){a=a.className;return(0,_.xa)(a)&&a.match(/\S+/g)||[]};_.Bi=function(a,b){for(var c=(0,_.Ai)(a),d=(0,_.zg)(arguments,1),f=c.length+d.length,g=c,h=0;h<d.length;h++)(0,_.ug)(g,d[h])||g.push(d[h]);a.className=c.join(" ");return c.length==f};_.Ci=function(a,b){var c=b||window.document;return c.querySelectorAll&&c.querySelector?c.querySelectorAll("."+a):c.getElementsByClassName?c.getElementsByClassName(a):(0,_.Di)(window.document,"*",a,b)};
_.Ei=function(a,b){var c=b||window.document,d=_.p;return(d=c.querySelectorAll&&c.querySelector?c.querySelector("."+a):(0,_.Ci)(a,b)[0])||_.p};
_.Di=function(a,b,c,d){a=d||a;b=b&&"*"!=b?b.toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(b||c))return a.querySelectorAll(b+(c?"."+c:""));if(c&&a.getElementsByClassName){a=a.getElementsByClassName(c);if(b){d={};for(var f=0,g=0,h;h=a[g];g++)b==h.nodeName&&(d[f++]=h);d.length=f;return d}return a}a=a.getElementsByTagName(b||"*");if(c){d={};for(g=f=0;h=a[g];g++)b=h.className,"function"==typeof b.split&&(0,_.ug)(b.split(/\s+/),c)&&(d[f++]=h);d.length=f;return d}return a};
_.Fi=function(a,b){(0,_.ti)(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:d in Gi?a.setAttribute(Gi[d],b):(0,_.Hf)(d,"aria-")||(0,_.Hf)(d,"data-")?a.setAttribute(d,b):a[d]=b})};
_.Hi=function(a,b){var c=b[0],d=b[1];if(!Ii&&d&&(d.name||d.type)){c=["<",c];d.name&&c.push(' name="',(0,_.Bf)(d.name),'"');if(d.type){c.push(' type="',(0,_.Bf)(d.type),'"');var f={};(0,_.yi)(f,d);delete f.type;d=f}c.push(">");c=c.join("")}c=a.createElement(c);d&&((0,_.xa)(d)?c.className=d:(0,_.ra)(d)?_.Bi.apply(_.p,[c].concat(d)):(0,_.Fi)(c,d));2<b.length&&(0,_.Ji)(a,c,b,2);return c};
_.Ji=function(a,b,c,d){function f(c){c&&b.appendChild((0,_.xa)(c)?a.createTextNode(c):c)}for(;d<c.length;d++){var g=c[d];!(0,_.ta)(g)||(0,_.pg)(g)&&0<g.nodeType?f(g):(0,_.Ag)(Ki(g)?(0,_.yg)(g):g,f)}};_.Li=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b)};_.Mi=function(a){return a&&a.parentNode?a.parentNode.removeChild(a):_.p};_.Ni=function(a){var b,c=a.parentNode;if(c&&11!=c.nodeType){if(a.removeNode)return a.removeNode(_.t);for(;b=a.firstChild;)c.insertBefore(b,a);return(0,_.Mi)(a)}};
_.Oi=function(a){return a.firstElementChild!=_.l?a.firstElementChild:(0,_.Pi)(a.firstChild,_.n)};_.Pi=function(a,b){for(;a&&1!=a.nodeType;)a=b?a.nextSibling:a.previousSibling;return a};_.Qi=function(a,b){if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||Boolean(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a};_.Ri=function(a){var b=[];(0,_.Si)(a,b,_.t);return b.join("")};
_.Si=function(a,b,c){if(!(a.nodeName in Ti))if(3==a.nodeType)c?b.push(String(a.nodeValue).replace(/(\r\n|\r|\n)/g,"")):b.push(a.nodeValue);else if(a.nodeName in Ui)b.push(Ui[a.nodeName]);else for(a=a.firstChild;a;)(0,_.Si)(a,b,c),a=a.nextSibling};var Ki=function(a){if(a&&"number"==typeof a.length){if((0,_.pg)(a))return"function"==typeof a.item||"string"==typeof a.item;if((0,_.qg)(a))return"function"==typeof a.item}return _.t};_.Vi=function(a){this.A=a||_.la.document||window.document};
var Ii=!_.T||(0,_.Of)(9);!_.ag&&!_.T||_.T&&(0,_.Of)(9)||_.ag&&(0,_.Lf)("1.9.1");_.Wi=_.T&&!(0,_.Lf)("9");var Gi={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"},Ti={SCRIPT:1,STYLE:1,HEAD:1,IFRAME:1,OBJECT:1},Ui={IMG:" ",BR:"\n"};_.F=_.Vi.prototype;_.F.M=function(a){return(0,_.xa)(a)?this.A.getElementById(a):a};_.F.$=function(a,b,c){return(0,_.Hi)(this.A,arguments)};_.F.createElement=function(a){return this.A.createElement(a)}; _.F.Na=function(){return this.A.parentWindow||this.A.defaultView};_.F.appendChild=function(a,b){a.appendChild(b)};_.F.Hu=_.Li;_.F.removeNode=_.Mi;_.F.pB=_.Ni;_.F.Bg=_.Oi;_.F.contains=_.Qi;

_.Xi=function(a,b){for(var c=a.split("."),d=b||_.la,f;f=c.shift();)if(d[f]!=_.p)d=d[f];else return _.p;return d};_.Yi=function(a){_.Zi[_.Zi.length]=a;if(_.$i)for(var b=0;b<_.aj.length;b++)a((0,_.H)(_.aj[b].A,_.aj[b]))};var bj=function(a){bj[" "](a);return a};_.cj=function(a,b){this.type=a;this.currentTarget=this.target=b};_.dj=function(a,b){a&&this.ya(a,b)};_.ej=function(a){try{return!(!a||!a[fj])}catch(b){return _.t}};
var gj=function(a,b,c,d,f,g){this.Bd=a;this.A=b;this.src=c;this.type=d;this.capture=!!f;this.Ve=g;this.key=++hj;this.mh=this.Bj=_.t};var ij=function(a){a.mh=_.n;a.Bd=_.p;a.A=_.p;a.src=_.p;a.Ve=_.p};var jj=function(a){this.src=a;this.A={};this.B=0};var kj=function(a,b){var c=b.type;if(!(c in a.A))return _.t;var d=(0,_.wg)(a.A[c],b);d&&(ij(b),0==a.A[c].length&&(delete a.A[c],a.B--));return d};_.lj=function(a,b,c,d,f){a=a.A[b];b=-1;a&&(b=mj(a,c,d,f));return-1<b?a[b]:_.p};
var mj=function(a,b,c,d){for(var f=0;f<a.length;++f){var g=a[f];if(!g.mh&&g.Bd==b&&g.capture==!!c&&g.Ve==d)return f}return-1};_.nj=function(a,b,c,d,f){if((0,_.ra)(b)){for(var g=0;g<b.length;g++)(0,_.nj)(a,b[g],c,d,f);return _.p}c=(0,_.oj)(c);return(0,_.ej)(a)?a.T(b,c,d,f):pj(a,b,c,_.t,d,f)};
var pj=function(a,b,c,d,f,g){b||(0,_.k)(Error("v"));var h=!!f,m=(0,_.qj)(a);m||(a[rj]=m=new jj(a));c=m.add(b,c,d,f,g);if(c.A)return c;d=sj();c.A=d;d.src=a;d.Bd=c;a.addEventListener?a.addEventListener(b,d,h):a.attachEvent(b in tj?tj[b]:tj[b]="on"+b,d);uj++;return c};var sj=function(){var a=vj,b=wj?function(c){return a.call(b.src,b.Bd,c)}:function(c){c=a.call(b.src,b.Bd,c);if(!c)return c};return b};
_.xj=function(a,b,c,d,f){if((0,_.ra)(b)){for(var g=0;g<b.length;g++)(0,_.xj)(a,b[g],c,d,f);return _.p}c=(0,_.oj)(c);return(0,_.ej)(a)?a.nd.add(b,c,_.n,d,f):pj(a,b,c,_.n,d,f)};_.yj=function(a,b,c,d,f){if((0,_.ra)(b)){for(var g=0;g<b.length;g++)(0,_.yj)(a,b[g],c,d,f);return _.p}c=(0,_.oj)(c);if((0,_.ej)(a))return a.jb(b,c,d,f);if(!a)return _.t;d=!!d;if(a=(0,_.qj)(a))if(b=(0,_.lj)(a,b,c,d,f))return(0,_.zj)(b);return _.t};
_.zj=function(a){if((0,_.rg)(a)||!a||a.mh)return _.t;var b=a.src;if((0,_.ej)(b))return kj(b.nd,a);var c=a.type,d=a.A;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent&&b.detachEvent(c in tj?tj[c]:tj[c]="on"+c,d);uj--;(c=(0,_.qj)(b))?(kj(c,a),0==c.B&&(c.src=_.p,b[rj]=_.p)):ij(a);return _.n};var Aj=function(a,b,c,d){var f=1;if(a=(0,_.qj)(a))if(b=a.A[b])for(b=(0,_.yg)(b),a=0;a<b.length;a++){var g=b[a];g&&g.capture==c&&!g.mh&&(f&=Bj(g,d)!==_.t)}return Boolean(f)};
var Bj=function(a,b){var c=a.Bd,d=a.Ve||a.src;a.Bj&&(0,_.zj)(a);return c.call(d,b)};
var vj=function(a,b){if(a.mh)return _.n;if(!wj){var c=b||(0,_.Xi)("window.event"),d=new _.dj(c,this),f=_.n;if(!(0>c.keyCode||c.returnValue!=_.l)){t:{var g=_.t;if(0==c.keyCode)try{c.keyCode=-1;break t}catch(h){g=_.n}if(g||c.returnValue==_.l)c.returnValue=_.n}c=[];for(g=d.currentTarget;g;g=g.parentNode)c.push(g);for(var g=a.type,m=c.length-1;!d.ef&&0<=m;m--)d.currentTarget=c[m],f&=Aj(c[m],g,_.n,d);for(m=0;!d.ef&&m<c.length;m++)d.currentTarget=c[m],f&=Aj(c[m],g,_.t,d)}return f}return Bj(a,new _.dj(b,
this))};_.qj=function(a){a=a[rj];return a instanceof jj?a:_.p};_.oj=function(a){return(0,_.qg)(a)?a:a[Cj]||(a[Cj]=function(b){return a.handleEvent(b)})};_.Dj=function(){this.nd=new jj(this);this.cb=this};var Ej=function(a,b,c,d){b=a.nd.A[b];if(!b)return _.n;b=(0,_.yg)(b);for(var f=_.n,g=0;g<b.length;++g){var h=b[g];if(h&&!h.mh&&h.capture==c){var m=h.Bd,q=h.Ve||h.src;h.Bj&&kj(a.nd,h);f=m.call(q,d)!==_.t&&f}}return f&&d.bw!=_.t};_.Zi=[];_.aj=[];_.$i=_.t;
bj[" "]=_.sg;var Gj;var wj;_.Fj=!_.T||(0,_.Of)(9);wj=!_.T||(0,_.Of)(9);Gj=_.T&&!(0,_.Lf)("9");!_.bg||(0,_.Lf)("528");_.ag&&(0,_.Lf)("1.9b")||_.T&&(0,_.Lf)("8")||_.$f&&(0,_.Lf)("9.5")||_.bg&&(0,_.Lf)("528");_.ag&&!(0,_.Lf)("8")||_.T&&(0,_.Lf)("9");_.F=_.cj.prototype;_.F.U=(0,_.ea)();_.F.ha=(0,_.ea)();_.F.ef=_.t;_.F.defaultPrevented=_.t;_.F.bw=_.n;_.F.stopPropagation=function(){this.ef=_.n};_.F.preventDefault=function(){this.defaultPrevented=_.n;this.bw=_.t};_.Hj=_.T?"focusin":"DOMFocusIn";_.Ij=_.T?"focusout":"DOMFocusOut";_.Jj=_.bg?"webkitTransitionEnd":_.$f?"otransitionend":"transitionend";(0,_.I)(_.dj,_.cj);_.F=_.dj.prototype;_.F.target=_.p;_.F.relatedTarget=_.p;_.F.offsetX=0;_.F.offsetY=0;_.F.clientX=0;_.F.clientY=0;_.F.screenX=0;_.F.screenY=0;_.F.button=0;_.F.keyCode=0;_.F.charCode=0;_.F.ctrlKey=_.t;_.F.altKey=_.t;_.F.shiftKey=_.t;_.F.metaKey=_.t;_.F.ip=_.t;_.F.Pb=_.p;
_.F.ya=function(a,b){var c=this.type=a.type;_.cj.call(this,c);this.target=a.target||a.srcElement;this.currentTarget=b;var d=a.relatedTarget;if(d){if(_.ag){var f;t:{try{bj(d.nodeName);f=_.n;break t}catch(g){}f=_.t}f||(d=_.p)}}else"mouseover"==c?d=a.fromElement:"mouseout"==c&&(d=a.toElement);this.relatedTarget=d;this.offsetX=_.bg||a.offsetX!==_.l?a.offsetX:a.layerX;this.offsetY=_.bg||a.offsetY!==_.l?a.offsetY:a.layerY;this.clientX=a.clientX!==_.l?a.clientX:a.pageX;this.clientY=a.clientY!==_.l?a.clientY:
a.pageY;this.screenX=a.screenX||0;this.screenY=a.screenY||0;this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.ip=_.Vf?a.metaKey:a.ctrlKey;this.state=a.state;this.Pb=a;a.defaultPrevented&&this.preventDefault();delete this.ef};
_.F.stopPropagation=function(){_.dj.O.stopPropagation.call(this);this.Pb.stopPropagation?this.Pb.stopPropagation():this.Pb.cancelBubble=_.n};_.F.preventDefault=function(){_.dj.O.preventDefault.call(this);var a=this.Pb;if(a.preventDefault)a.preventDefault();else if(a.returnValue=_.t,Gj)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};_.F.AB=(0,_.u)("Pb");_.F.U=(0,_.ea)();
var fj="closure_listenable_"+(1E6*Math.random()|0),hj=0;jj.prototype.add=function(a,b,c,d,f){var g=this.A[a];g||(g=this.A[a]=[],this.B++);var h=mj(g,b,d,f);-1<h?(a=g[h],c||(a.Bj=_.t)):(a=new gj(b,_.p,this.src,a,!!d,f),a.Bj=c,g.push(a));return a};jj.prototype.remove=function(a,b,c,d){if(!(a in this.A))return _.t;var f=this.A[a];b=mj(f,b,c,d);return-1<b?(ij(f[b]),_.xg.splice.call(f,b,1),0==f.length&&(delete this.A[a],this.B--),_.n):_.t};jj.prototype.kk=function(a,b){var c=this.A[a],d=[];if(c)for(var f=0;f<c.length;++f){var g=c[f];g.capture==b&&d.push(g)}return d};
var rj="closure_lm_"+(1E6*Math.random()|0),tj={},uj=0,Cj="__closure_events_fn_"+(1E9*Math.random()>>>0);(0,_.Yi)(function(a){vj=a(vj)});(0,_.I)(_.Dj,_.qi);_.Dj.prototype[fj]=_.n;_.F=_.Dj.prototype;_.F.dl=_.p;_.F.Qp=(0,_.ia)("dl");_.F.addEventListener=function(a,b,c,d){(0,_.nj)(this,a,b,c,d)};_.F.removeEventListener=function(a,b,c,d){(0,_.yj)(this,a,b,c,d)};
_.F.dispatchEvent=function(a){var b,c=this.dl;if(c){b=[];for(var d=1;c;c=c.dl)b.push(c),++d}c=this.cb;d=a.type||a;if((0,_.xa)(a))a=new _.cj(a,c);else if(a instanceof _.cj)a.target=a.target||c;else{var f=a;a=new _.cj(d,c);(0,_.yi)(a,f)}var f=_.n,g;if(b)for(var h=b.length-1;!a.ef&&0<=h;h--)g=a.currentTarget=b[h],f=Ej(g,d,_.n,a)&&f;a.ef||(g=a.currentTarget=c,f=Ej(g,d,_.n,a)&&f,a.ef||(f=Ej(g,d,_.t,a)&&f));if(b)for(h=0;!a.ef&&h<b.length;h++)g=a.currentTarget=b[h],f=Ej(g,d,_.t,a)&&f;return f};
_.F.U=function(){_.Dj.O.U.call(this);if(this.nd){var a=this.nd,b=0,c;for(c in a.A){for(var d=a.A[c],f=0;f<d.length;f++)++b,ij(d[f]);delete a.A[c];a.B--}}this.dl=_.p};_.F.T=function(a,b,c,d){return this.nd.add(a,b,_.t,c,d)};_.F.jb=function(a,b,c,d){return this.nd.remove(a,b,c,d)};_.F.kk=function(a,b){return this.nd.kk(a,b)};

_.Kj=function(a){this.F=a;this.G={}};_.Lj=function(a){(0,_.ti)(a.G,_.zj);a.G={}};(0,_.I)(_.Kj,_.qi);var Mj=[];_.Kj.prototype.T=function(a,b,c,d,f){(0,_.ra)(b)||(Mj[0]=b,b=Mj);for(var g=0;g<b.length;g++){var h=(0,_.nj)(a,b[g],c||this,d||_.t,f||this.F||this);if(!h)break;this.G[h.key]=h}return this};
_.Kj.prototype.jb=function(a,b,c,d,f){if((0,_.ra)(b))for(var g=0;g<b.length;g++)this.jb(a,b[g],c,d,f);else c=c||this,f=f||this.F||this,c=(0,_.oj)(c),d=!!d,b=(0,_.ej)(a)?(0,_.lj)(a.nd,b,c,d,f):a?(a=(0,_.qj)(a))?(0,_.lj)(a,b,c,d,f):_.p:_.p,b&&((0,_.zj)(b),delete this.G[b.key]);return this};_.Kj.prototype.U=function(){_.Kj.O.U.call(this);(0,_.Lj)(this)};_.Kj.prototype.handleEvent=function(){(0,_.k)(Error("w"))};

_.Nj=function(a){return"CSS1Compat"==a.compatMode};_.Oj=function(a){return!_.bg&&(0,_.Nj)(a)?a.documentElement:a.body};_.Pj=function(a,b){this.width=a;this.height=b};_.Qj=function(a,b){this.x=(0,_.qa)(a)?a:0;this.y=(0,_.qa)(b)?b:0};_.Rj=function(a){return 9==a.nodeType?a:a.ownerDocument||a.document};
_.Sj=function(a){var b=(0,_.Oj)(a);a=a.parentWindow||a.defaultView;return _.T&&(0,_.Lf)("10")&&a.pageYOffset!=b.scrollTop?new _.Qj(b.scrollLeft,b.scrollTop):new _.Qj(a.pageXOffset||b.scrollLeft,a.pageYOffset||b.scrollTop)};_.Tj=function(a){a=a.document;a=(0,_.Nj)(a)?a.documentElement:a.body;return new _.Pj(a.clientWidth,a.clientHeight)};_.Uj=function(a){return(0,_.Sj)(a.A)};_.Vj=function(a){return(0,_.Nj)(a.A)};_.Wj=function(a){return a?a.parentWindow||a.defaultView:window};
_.Xj=function(a){return(0,_.Tj)(a||window)};_.Yj=function(a){for(var b;b=a.firstChild;)a.removeChild(b)};_.Zj=function(a){return a?new _.Vi((0,_.Rj)(a)):ak||(ak=new _.Vi)};_.bk=function(a){if(_.Wi&&"innerText"in a)a=a.innerText.replace(/(\r\n|\r|\n)/g,"\n");else{var b=[];(0,_.Si)(a,b,_.n);a=b.join("")}a=a.replace(/ \xAD /g," ").replace(/\xAD/g,"");a=a.replace(/\u200B/g,"");_.Wi||(a=a.replace(/ +/g," "));" "!=a&&(a=a.replace(/^\s*/,""));return a};
_.ck=function(a,b){if("textContent"in a)a.textContent=b;else if(a.firstChild&&3==a.firstChild.nodeType){for(;a.lastChild!=a.firstChild;)a.removeChild(a.lastChild);a.firstChild.data=b}else(0,_.Yj)(a),a.appendChild((0,_.Rj)(a).createTextNode(String(b)))};_.dk=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b.nextSibling)};_.ek=function(a){return(0,_.xa)(a)?window.document.getElementById(a):a};
var fk=function(a,b){var c=(0,_.xa)(b)?String(b).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08"):"\\s",c=c?"|["+c+"]+":"";return a.replace(RegExp("(^"+c+")([a-z])","g"),function(a,b,c){return b+c.toUpperCase()})};_.gk=function(a){return String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()})};_.hk=function(a,b){for(var c in b)a[c]=b[c]};_.ik=function(a,b,c){(0,_.xa)(b)?jk(a,c,b):(0,_.ti)(b,(0,_.Ea)(jk,a))};
var jk=function(a,b,c){(c=(0,_.kk)(a,c))&&(a.style[c]=b)};_.kk=function(a,b){var c=(0,_.gk)(b);if(a.style[c]===_.l){var d=(_.bg?"Webkit":_.ag?"Moz":_.T?"ms":_.$f?"O":_.p)+fk(b);if(a.style[d]!==_.l)return d}return c};_.lk=function(a,b){var c=(0,_.Rj)(a);return c.defaultView&&c.defaultView.getComputedStyle&&(c=c.defaultView.getComputedStyle(a,_.p))?c[b]||c.getPropertyValue(b)||"":""};_.mk=function(a,b){return a.currentStyle?a.currentStyle[b]:_.p};
_.nk=function(a,b){return(0,_.lk)(a,b)||(0,_.mk)(a,b)||a.style&&a.style[b]};_.ok=function(a){return(0,_.nk)(a,"position")};_.pk=function(a){a=a?(0,_.Rj)(a):window.document;return!_.T||(0,_.Of)(9)||(0,_.Vj)((0,_.Zj)(a))?a.documentElement:a.body};
var qk=function(a){var b;try{b=a.getBoundingClientRect()}catch(c){return{left:0,top:0,right:0,bottom:0}}_.T&&a.ownerDocument.body&&(a=a.ownerDocument,b.left-=a.documentElement.clientLeft+a.body.clientLeft,b.top-=a.documentElement.clientTop+a.body.clientTop);return b};
_.rk=function(a){if(_.T&&!(0,_.Of)(8))return a.offsetParent;var b=(0,_.Rj)(a),c=(0,_.nk)(a,"position"),d="fixed"==c||"absolute"==c;for(a=a.parentNode;a&&a!=b;a=a.parentNode)if(c=(0,_.nk)(a,"position"),d=d&&"static"==c&&a!=b.documentElement&&a!=b.body,!d&&(a.scrollWidth>a.clientWidth||a.scrollHeight>a.clientHeight||"fixed"==c||"absolute"==c||"relative"==c))return a;return _.p};
_.sk=function(a){var b,c=(0,_.Rj)(a),d=(0,_.nk)(a,"position"),f=_.ag&&c.getBoxObjectFor&&!a.getBoundingClientRect&&"absolute"==d&&(b=c.getBoxObjectFor(a))&&(0>b.screenX||0>b.screenY),g=new _.Qj(0,0),h=(0,_.pk)(c);if(a==h)return g;if(a.getBoundingClientRect)b=qk(a),a=(0,_.Uj)((0,_.Zj)(c)),g.x=b.left+a.x,g.y=b.top+a.y;else if(c.getBoxObjectFor&&!f)b=c.getBoxObjectFor(a),a=c.getBoxObjectFor(h),g.x=b.screenX-a.screenX,g.y=b.screenY-a.screenY;else{b=a;do{g.x+=b.offsetLeft;g.y+=b.offsetTop;b!=a&&(g.x+=
b.clientLeft||0,g.y+=b.clientTop||0);if(_.bg&&"fixed"==(0,_.ok)(b)){g.x+=c.body.scrollLeft;g.y+=c.body.scrollTop;break}b=b.offsetParent}while(b&&b!=a);if(_.$f||_.bg&&"absolute"==d)g.y-=c.body.offsetTop;for(b=a;(b=(0,_.rk)(b))&&b!=c.body&&b!=h;)g.x-=b.scrollLeft,_.$f&&"TR"==b.tagName||(g.y-=b.scrollTop)}return g};_.tk=function(a,b){var c=new _.Qj(0,0),d=(0,_.Wj)((0,_.Rj)(a)),f=a;do{var g=d==b?(0,_.sk)(f):(0,_.uk)(f);c.x+=g.x;c.y+=g.y}while(d&&d!=b&&(f=d.frameElement)&&(d=d.parent));return c};
_.uk=function(a){var b;if(a.getBoundingClientRect)b=qk(a),b=new _.Qj(b.left,b.top);else{b=(0,_.Uj)((0,_.Zj)(a));var c=(0,_.sk)(a);b=new _.Qj(c.x-b.x,c.y-b.y)}if(_.ag&&!(0,_.Lf)(12)){var d;_.T?d="-ms-transform":_.bg?d="-webkit-transform":_.$f?d="-o-transform":_.ag&&(d="-moz-transform");var f;d&&(f=(0,_.nk)(a,d));f||(f=(0,_.nk)(a,"transform"));a=f?(a=f.match(vk))?new _.Qj((0,window.parseFloat)(a[1]),(0,window.parseFloat)(a[2])):new _.Qj(0,0):new _.Qj(0,0);a=new _.Qj(b.x+a.x,b.y+a.y)}else a=b;return a};
_.wk=function(a,b,c){b instanceof _.Pj?(c=b.height,b=b.width):c==_.l&&(0,_.k)(Error("x"));a.style.width=(0,_.xk)(b,_.n);a.style.height=(0,_.xk)(c,_.n)};_.xk=function(a,b){"number"==typeof a&&(a=(b?Math.round(a):a)+"px");return a};_.yk=function(a){var b;var c=zk;if("none"!=(0,_.nk)(a,"display"))b=c(a);else{b=a.style;var d=b.display,f=b.visibility,g=b.position;b.visibility="hidden";b.position="absolute";b.display="inline";a=c(a);b.display=d;b.position=g;b.visibility=f;b=a}return b};
var zk=function(a){var b=a.offsetWidth,c=a.offsetHeight,d=_.bg&&!b&&!c;return(0,_.qa)(b)&&!d||!a.getBoundingClientRect?new _.Pj(b,c):(a=qk(a),new _.Pj(a.right-a.left,a.bottom-a.top))};_.Pj.prototype.ra=function(){return new _.Pj(this.width,this.height)};_.Pj.prototype.wc=function(){return!(this.width*this.height)};_.Pj.prototype.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};
_.Pj.prototype.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};_.Qj.prototype.ra=function(){return new _.Qj(this.x,this.y)};_.Qj.prototype.floor=function(){this.x=Math.floor(this.x);this.y=Math.floor(this.y);return this};_.Qj.prototype.round=function(){this.x=Math.round(this.x);this.y=Math.round(this.y);return this};_.Qj.prototype.translate=function(a,b){a instanceof _.Qj?(this.x+=a.x,this.y+=a.y):(this.x+=a,(0,_.rg)(b)&&(this.y+=b));return this}; var ak;
var vk;_.Ak=_.ag?"MozUserSelect":_.bg?"WebkitUserSelect":_.p;vk=/matrix\([0-9\.\-]+, [0-9\.\-]+, [0-9\.\-]+, [0-9\.\-]+, ([0-9\.\-]+)p?x?, ([0-9\.\-]+)p?x?\)/;
_.Bk=function(a,b,c,d){this.top=a;this.right=b;this.bottom=c;this.left=d};_.Ck=function(a,b,c,d){if(/^\d+px?$/.test(b))return(0,window.parseInt)(b,10);var f=a.style[c],g=a.runtimeStyle[c];a.runtimeStyle[c]=a.currentStyle[c];a.style[c]=b;b=a.style[d];a.style[c]=f;a.runtimeStyle[c]=g;return b};var Dk=function(a,b){if("none"==(0,_.mk)(a,b+"Style"))return 0;var c=(0,_.mk)(a,b+"Width");return c in Ek?Ek[c]:(0,_.Ck)(a,c,"left","pixelLeft")};
_.Fk=function(a){if(_.T&&!(0,_.Of)(9)){var b=Dk(a,"borderLeft"),c=Dk(a,"borderRight"),d=Dk(a,"borderTop");a=Dk(a,"borderBottom");return new _.Bk(d,c,a,b)}b=(0,_.lk)(a,"borderLeftWidth");c=(0,_.lk)(a,"borderRightWidth");d=(0,_.lk)(a,"borderTopWidth");a=(0,_.lk)(a,"borderBottomWidth");return new _.Bk((0,window.parseFloat)(d),(0,window.parseFloat)(c),(0,window.parseFloat)(a),(0,window.parseFloat)(b))};_.Gk=function(a){return"rtl"==(0,_.nk)(a,"direction")};
_.Hk=function(a,b,c,d){this.left=a;this.top=b;this.width=c;this.height=d};_.Ik=function(a,b){var c=(0,_.Zj)(b),d=_.p,d=c.A;if(_.T&&d.createStyleSheet)c=d=d.createStyleSheet(),_.T?c.cssText=a:c.innerHTML=a;else{var f=(0,_.Di)(c.A,"head",_.l,_.l)[0];f||(d=(0,_.Di)(c.A,"body",_.l,_.l)[0],f=c.$("head"),d.parentNode.insertBefore(f,d));var g=d=c.$("style");_.T?g.cssText=a:g.innerHTML=a;c.appendChild(f,d)}return d};_.Jk=function(a,b){a.style.display=b?"":"none"};
_.Kk=function(a,b){var c=a.style;"opacity"in c?c.opacity=b:"MozOpacity"in c?c.MozOpacity=b:"filter"in c&&(c.filter=""===b?"":"alpha(opacity="+100*b+")")};_.Lk=function(a,b,c){var d,f=_.ag&&(_.Vf||_.fg)&&(0,_.Lf)("1.9");b instanceof _.Qj?(d=b.x,b=b.y):(d=b,b=c);a.style.left=(0,_.xk)(d,f);a.style.top=(0,_.xk)(b,f)};_.Mk=function(a,b,c){var d={},f;for(f in a)b.call(c,a[f],f,a)&&(d[f]=a[f]);return d};_.F=_.Bk.prototype;_.F.ra=function(){return new _.Bk(this.top,this.right,this.bottom,this.left)};
_.F.contains=function(a){return this&&a?a instanceof _.Bk?a.left>=this.left&&a.right<=this.right&&a.top>=this.top&&a.bottom<=this.bottom:a.x>=this.left&&a.x<=this.right&&a.y>=this.top&&a.y<=this.bottom:_.t};_.F.floor=function(){this.top=Math.floor(this.top);this.right=Math.floor(this.right);this.bottom=Math.floor(this.bottom);this.left=Math.floor(this.left);return this};
_.F.round=function(){this.top=Math.round(this.top);this.right=Math.round(this.right);this.bottom=Math.round(this.bottom);this.left=Math.round(this.left);return this};_.F.translate=function(a,b){a instanceof _.Qj?(this.left+=a.x,this.right+=a.x,this.top+=a.y,this.bottom+=a.y):(this.left+=a,this.right+=a,(0,_.rg)(b)&&(this.top+=b,this.bottom+=b));return this};var Ek={thin:2,medium:4,thick:6};_.F=_.Hk.prototype;_.F.ra=function(){return new _.Hk(this.left,this.top,this.width,this.height)};
_.F.contains=function(a){return a instanceof _.Hk?this.left<=a.left&&this.left+this.width>=a.left+a.width&&this.top<=a.top&&this.top+this.height>=a.top+a.height:a.x>=this.left&&a.x<=this.left+this.width&&a.y>=this.top&&a.y<=this.top+this.height};_.F.floor=function(){this.left=Math.floor(this.left);this.top=Math.floor(this.top);this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};
_.F.round=function(){this.left=Math.round(this.left);this.top=Math.round(this.top);this.width=Math.round(this.width);this.height=Math.round(this.height);return this};_.F.translate=function(a,b){a instanceof _.Qj?(this.left+=a.x,this.top+=a.y):(this.left+=a,(0,_.rg)(b)&&(this.top+=b));return this};

_.Nk=function(a){return new _.Bk(a.top,a.left+a.width,a.top+a.height,a.left)};var Ok=function(a,b){var c=(0,_.mk)(a,b);return c?(0,_.Ck)(a,c,"left","pixelLeft"):0};
_.Pk=function(a){var b;if(_.T){b=Ok(a,"paddingLeft");var c=Ok(a,"paddingRight"),d=Ok(a,"paddingTop");a=Ok(a,"paddingBottom");b=new _.Bk(d,c,a,b)}else b=(0,_.lk)(a,"paddingLeft"),c=(0,_.lk)(a,"paddingRight"),d=(0,_.lk)(a,"paddingTop"),a=(0,_.lk)(a,"paddingBottom"),b=new _.Bk((0,window.parseFloat)(d),(0,window.parseFloat)(c),(0,window.parseFloat)(a),(0,window.parseFloat)(b));return b};
_.Qk=function(a){if(1==a.nodeType)return(0,_.uk)(a);var b=(0,_.qg)(a.AB),c=a;a.targetTouches?c=a.targetTouches[0]:b&&a.Pb.targetTouches&&(c=a.Pb.targetTouches[0]);return new _.Qj(c.clientX,c.clientY)};var Rk=function(a,b){return new _.Qj(a.x-b.x,a.y-b.y)};_.Sk=function(a){var b=(0,_.sk)(a);a=(0,_.yk)(a);return new _.Hk(b.x,b.y,a.width,a.height)};
_.Tk=function(a){for(var b=new _.Bk(0,window.Infinity,window.Infinity,0),c=(0,_.Zj)(a),d=c.A.body,f=c.A.documentElement,g=(0,_.Oj)(c.A);a=(0,_.rk)(a);)if(!(_.T&&0==a.clientWidth||_.bg&&0==a.clientHeight&&a==d||a==d||a==f||"visible"==(0,_.nk)(a,"overflow"))){var h=(0,_.sk)(a),m;m=a;if(_.ag&&!(0,_.Lf)("1.9")){var q=(0,window.parseFloat)((0,_.lk)(m,"borderLeftWidth"));if((0,_.Gk)(m))var r=m.offsetWidth-m.clientWidth-q-(0,window.parseFloat)((0,_.lk)(m,"borderRightWidth")),q=q+r;m=new _.Qj(q,(0,window.parseFloat)((0,_.lk)(m,
"borderTopWidth")))}else m=new _.Qj(m.clientLeft,m.clientTop);h.x+=m.x;h.y+=m.y;b.top=Math.max(b.top,h.y);b.right=Math.min(b.right,h.x+a.clientWidth);b.bottom=Math.min(b.bottom,h.y+a.clientHeight);b.left=Math.max(b.left,h.x)}d=g.scrollLeft;g=g.scrollTop;b.left=Math.max(b.left,d);b.top=Math.max(b.top,g);c=(0,_.Xj)(c.Na());b.right=Math.min(b.right,d+c.width);b.bottom=Math.min(b.bottom,g+c.height);return 0<=b.top&&0<=b.left&&b.bottom>b.top&&b.right>b.left?b:_.p};
_.Uk=function(a,b,c,d){c||(a=a.parentNode);c=d==_.p;for(var f=0;a&&(c||f<=d);){if(b(a))return a;a=a.parentNode;f++}return _.p};_.Vk=function(a,b){return(0,_.ug)((0,_.Ai)(a),b)};
_.Wk=function(a,b,c,d,f,g,h,m,q){var r=(0,_.Xk)(c),s=(0,_.Sk)(a),v=(0,_.Tk)(a);if(v){var w=new _.Hk(v.left,v.top,v.right-v.left,v.bottom-v.top),v=Math.max(s.left,w.left),z=Math.min(s.left+s.width,w.left+w.width);if(v<=z){var E=Math.max(s.top,w.top),w=Math.min(s.top+s.height,w.top+w.height);E<=w&&(s.left=v,s.top=E,s.width=z-v,s.height=w-E)}}v=(0,_.Zj)(a);E=(0,_.Zj)(c);v.A!=E.A&&(z=v.A.body,E=(0,_.tk)(z,E.Na()),E=Rk(E,(0,_.sk)(z)),_.T&&!(0,_.Vj)(v)&&(E=Rk(E,(0,_.Uj)(v))),s.left+=E.x,s.top+=E.y);a=(b&
4&&(0,_.Gk)(a)?b^2:b)&-5;s=new _.Qj(a&2?s.left+s.width:s.left,a&1?s.top+s.height:s.top);s=Rk(s,r);f&&(s.x+=(a&2?-1:1)*f.x,s.y+=(a&1?-1:1)*f.y);var D;if(h)if(q)D=q;else if(D=(0,_.Tk)(c))D.top-=r.y,D.right-=r.x,D.bottom-=r.y,D.left-=r.x;return(0,_.Yk)(s,c,d,g,D,h,m)};
_.Xk=function(a){var b;if(a=a.offsetParent){var c="HTML"==a.tagName||"BODY"==a.tagName;c&&"static"==(0,_.ok)(a)||(b=(0,_.sk)(a),c||(c=(c=(0,_.Gk)(a))&&_.ag?-a.scrollLeft:!c||_.T&&(0,_.Lf)("8")||"visible"==(0,_.nk)(a,"overflowX")?a.scrollLeft:a.scrollWidth-a.clientWidth-a.scrollLeft,b=Rk(b,new _.Qj(c,a.scrollTop))))}return b||new _.Qj};
_.Yk=function(a,b,c,d,f,g,h){a=a.ra();var m=0,q=(c&4&&(0,_.Gk)(b)?c^2:c)&-5;c=(0,_.yk)(b);h=h?h.ra():c.ra();if(d||0!=q)q&2?a.x-=h.width+(d?d.right:0):d&&(a.x+=d.left),q&1?a.y-=h.height+(d?d.bottom:0):d&&(a.y+=d.top);if(g&&(f?(m=a,d=0,65==(g&65)&&(m.x<f.left||m.x>=f.right)&&(g&=-2),132==(g&132)&&(m.y<f.top||m.y>=f.bottom)&&(g&=-5),m.x<f.left&&g&1&&(m.x=f.left,d|=1),m.x<f.left&&m.x+h.width>f.right&&g&16&&(h.width=Math.max(h.width-(m.x+h.width-f.right),0),d|=4),m.x+h.width>f.right&&g&1&&(m.x=Math.max(f.right-
h.width,f.left),d|=1),g&2&&(d=d|(m.x<f.left?16:0)|(m.x+h.width>f.right?32:0)),m.y<f.top&&g&4&&(m.y=f.top,d|=2),m.y<=f.top&&m.y+h.height<f.bottom&&g&32&&(h.height=Math.max(h.height-(f.top-m.y),0),m.y=f.top,d|=8),m.y>=f.top&&m.y+h.height>f.bottom&&g&32&&(h.height=Math.max(h.height-(m.y+h.height-f.bottom),0),d|=8),m.y+h.height>f.bottom&&g&4&&(m.y=Math.max(f.bottom-h.height,f.top),d|=2),g&8&&(d=d|(m.y<f.top?64:0)|(m.y+h.height>f.bottom?128:0)),m=d):m=256,m&496))return m;(0,_.Lk)(b,a);c==h||c&&h&&c.width==
h.width&&c.height==h.height||(f=(0,_.Vj)((0,_.Zj)((0,_.Rj)(b))),!_.T||f&&(0,_.Lf)("8")?(b=b.style,_.ag?b.MozBoxSizing="border-box":_.bg?b.WebkitBoxSizing="border-box":b.boxSizing="border-box",b.width=Math.max(h.width,0)+"px",b.height=Math.max(h.height,0)+"px"):(a=b.style,f?(f=(0,_.Pk)(b),b=(0,_.Fk)(b),a.pixelWidth=h.width-b.left-f.left-f.right-b.right,a.pixelHeight=h.height-b.top-f.top-f.bottom-b.bottom):(a.pixelWidth=h.width,a.pixelHeight=h.height)));return m};


_.Zk=function(){var a=window.document,b=0;if(a){var b=(0,_.Tj)(window).height,c=a.body,d=a.documentElement;if((0,_.Nj)(a)&&d.scrollHeight)b=d.scrollHeight!=b?d.scrollHeight:d.offsetHeight;else{var a=d.scrollHeight,f=d.offsetHeight;d.clientHeight!=f&&(a=c.scrollHeight,f=c.offsetHeight);b=a>b?a>f?a:f:a<f?a:f}}return b};_.$k=function(a){this.N=a;this.A=a.Ja()};
var al=function(a){var b=a.N.ob();if(a.A.anchorBox&&b&&b.Fa())b=(0,_.sk)(b.Fa()),a.A.anchorBox.left+=b.x,a.A.anchorBox.top+=b.y;else{b=a.A.anchor;if("_default"!=b&&"_iframe"!=b){var c=(0,_.ek)(b);if(c)a.A.anchorBox=(0,_.Sk)(c);else{(0,_.Pa)("Anchor not found in DOM: "+b+'. Falling back to "_default".');a.A.anchor="_default";return}}"_iframe"==b&&(b=(0,_.Xj)(),a.A.anchorBox=new _.Hk(0,0,b.width,b.height))}a.A.anchor=""};_.bl=function(a){_.$k.call(this,a)};
_.cl=function(a){if(a.V)return a.V;var b=a.A;!b.anchorBox&&b.anchor&&al(a);var c=a.N.ob();if("_default"==b.anchor&&c){var d=(0,_.Sk)((0,_.ek)(c.ka()));b.anchorBox=d}if(!b.anchorBox)return(0,_.Pa)("No anchor box defined."),_.p;b=new _.Qj(b.anchorBox.left,b.anchorBox.top);c&&(c=(0,_.tk)(c.Fa(),window),a.ja=new _.Qj,a.ja.x=c.x,a.ja.y=c.y,b.x+=c.x,b.y+=c.y,(0,_.dl)(window,b));a.Ma=b;c=(0,_.el)(a,_.n);a.V=window.document.createElement("ins");a.V.style.cssText=c;window.document.body.appendChild(a.V);return a.V};
_.el=function(a,b){var c=a.A;return"position: absolute !important;background-color: transparent !important;left: "+a.Ma.x+"px !important;top: "+a.Ma.y+"px !important;width: "+c.anchorBox.width+"px !important;height: "+c.anchorBox.height+"px !important;z-index: -10000 !important;display: "+(b?"block":"none")+" !important;"};
_.fl=function(a,b){var c=0,d=0;if(b.pageX||b.pageY)c=b.pageX,d=b.pageY;else if(b.clientX||b.clientY){var d=b.target?b.target:b.srcElement,c=d.ownerDocument&&d.ownerDocument.parentWindow?d.ownerDocument.parentWindow:window,f=0,d=0;_.T?(f=c.document.documentElement.scrollLeft,d=c.document.documentElement.scrollTop):(f=c.pageXOffset,d=c.pageYOffset);c=b.clientX+f;d=b.clientY+d}d=new _.Qj(c,d);return(c=(0,_.Nk)((0,_.Sk)(a)))&&c.contains(d)};
_.dl=function(a,b){var c=window.document.body,d=(0,_.sk)(c),c=c.currentStyle||a.getComputedStyle(c,"");c.position&&"static"!=c.position&&(b.x-=d.x,b.y-=d.y)};_.gl=function(a){var b=a.N.ob()&&a.N.ob().ka(),b=b&&b.style.zIndex?(0,window.parseInt)(b.style.zIndex,10)+1:0;return Math.min(2147483647,Math.max(2E9,a.A.zIndex||b))};
_.hl=function(a,b,c,d,f){f=f||{x:0,y:0};if(il[b]){var g=(0,_.yk)(a).width/2;f.x="top-right"==d||"bottom-right"==d?f.x+g:f.x-g}il[d]&&(g=(0,_.yk)(c).width/2,f.x+=g);jl[b]&&(g=(0,_.yk)(a).height/2,f.y="right-bottom"==d||"left-bottom"==d?f.y+g:f.y-g);jl[d]&&(f.y+=(0,_.yk)(c).height/2);(0,_.Wk)(c,kl[d],a,kl[b],new _.Qj(f.x,f.y));d=(0,_.Uk)(a,function(a){return a==window.document?_.t:(a=(0,_.ok)(a))&&"static"!=a});c=b=0;d&&(c=(0,_.sk)(d),b=-c.x,c=-c.y);a=a.style;(0,window.parseInt)(a.left,10)<b&&(a.left=
b+"px");(0,window.parseInt)(a.top,10)<c&&(a.top=c+"px")};_.ll=function(a){_.$k.call(this,a.N);this.F=a;this.B=_.p};var ml=function(){_.Dj.call(this);this.A=[]};if("undefined"===typeof nl)var nl={};_.$k.prototype.Pa=function(){al(this)};_.$k.prototype.onBeforeParentOpen=_.$k.prototype.Pa;
(0,_.I)(_.bl,_.$k);_.bl.prototype.open=function(){var a=this.A,b=window.document.createElement("ins");window.document.getElementById(a.container).appendChild(b);b.style.display="block";(0,_.ik)(b,a.containerCss);this.N.Gd(b);this.N.Ic(b)};_.bl.prototype.Jb=function(){window.document.getElementById(this.N.id).style.height=this.N.height+"px"};_.bl.prototype.close=function(){(0,_.Mi)(this.N.ka());(0,_.Mi)(this.V);this.V=_.p};
var kl={"bottom-center":1,"bottom-end":7,"bottom-left":1,"bottom-right":3,"bottom-start":5,"left-bottom":1,"left-center":0,"left-top":0,"right-bottom":3,"right-center":2,"right-top":2,"top-center":0,"top-end":6,"top-left":0,"top-right":2,"top-start":4},il={"bottom-center":_.n,"top-center":_.n},jl={"left-center":_.n,"right-center":_.n};
(0,_.I)(_.ll,_.bl);_.ll.prototype.Pa=function(){this.F.Pa()};_.ll.prototype.onBeforeParentOpen=_.ll.prototype.Pa;_.ll.prototype.open=function(){this.F.open();if(this.A.closeClickDetection||this.A.hideClickDetection)this.B=(0,_.nj)(window.document,["click","touchstart"],(0,_.H)(this.C,this),_.t)};_.ll.prototype.open=_.ll.prototype.open;_.ll.prototype.Jb=function(a){this.F.Jb(a)};_.ll.prototype.onready=_.ll.prototype.Jb;_.ll.prototype.D=function(a){this.F.onRenderStart&&this.F.onRenderStart(a)};
_.ll.prototype.onRenderStart=_.ll.prototype.D;_.ll.prototype.close=function(){if(this.A.closeClickDetection||this.A.hideClickDetection)(0,_.zj)(this.B),this.B=_.p;this.F.close()};_.ll.prototype.close=_.ll.prototype.close;_.ll.prototype.C=function(a){(0,_.fl)(this.N.ka(),a)||(this.A.hideClickDetection&&this.F.show?this.F.show(_.t):this.F.close())};
(0,_.I)(ml,_.Dj);ml.prototype.U=function(){for(var a in this.A)(0,_.zj)(a);this.A=[];this.D=_.la.clearTimeout(this.D);ml.O.U.call(this);this.dispatchEvent({type:"dispose"})};(0,_.G)("iframes.styles.createAnchor",function(){return new ml(["email","oid","o","cid"])},_.l);

_.Cl=function(a,b){(0,_.ra)(b)||(b=[b]);var c=(0,_.Cg)(b,function(a){return(0,_.xa)(a)?a:a.mF+" "+a.duration+"s "+a.timing+" "+a.Vh+"s"});(0,_.ik)(a,"transition",c.join(","))};
_.Dl=function(){if(!(0,_.qa)(El))if(_.T)El=(0,_.Lf)("10.0");else{var a=window.document.createElement("div"),b=_.bg?"-webkit":_.ag?"-moz":_.T?"-ms":_.$f?"-o":_.p;a.innerHTML='<div style="'+(b?b+"-transition:opacity 1s linear;":"")+'transition:opacity 1s linear;">';a=a.firstChild;b=a.style[(0,_.gk)("transition")];El=""!=("undefined"!==typeof b?b:a.style[(0,_.kk)(a,"transition")]||"")}return El};var El;

var Fl=function(a,b,c,d,f){this.width=a;this.height=b;this.A=c;this.B=d;this.opacity=f};var Gl=function(a,b,c,d){return new Fl(b==_.l?a.width:b,c==_.l?a.height:c,a.A,a.B,d==_.l?a.opacity:d)};_.Hl=function(a){_.$k.call(this,a);this.Y=new _.Kj(this)};
_.Il=function(a){var b=+a.Qe(200,"widgetWidth","width"),c=+a.Qe(100,"widgetHeight","height"),d=a.Qe("auto","corner"),f=a.Qe({},"menuCss"),g=a.Qe(_.n,"hideOnClick");a.Le=!!a.Qe(_.n,"hideOnLeave");a.Cc=!!a.Qe((0,_.Dl)(),"useCss3Transition");a.ig=!!a.Qe(_.n,"allowOffset");var h=window.document.createElement("div");a.B=h;var m=(0,_.cl)(a);m.parentNode.appendChild(h);var q=window.document.createElement("div");a.Q=q;h.appendChild(q);f.position="absolute";f.width=b+"px";f.height="0";f.border=f.border||"1px solid #aaa";
f.background=f.background||"#fff";f.zIndex=(0,_.gl)(a);f.overflow="hidden";f.boxShadow=f.MozBoxShadow=f.webkitBoxShadow=f.boxShadow||"0 2px 2px rgba(0,0,0,0.3)";(0,_.ik)(h,f);(0,_.ik)(q,{left:"-1000px",top:"-1000px",position:"absolute",width:b+"px",height:c+"px"});a.og=h.offsetWidth-b;a.sg=h.offsetHeight;f="auto"==d?["top","start"]:d.split("-");m=(0,_.Gk)(m);a.ua="bottom"==f[0];a.Da="right"==f[1]||"left"!=f[1]&&m;a.C=Jl(a,b,c,"auto"==d);a.gc=_.la.setTimeout((0,_.H)(a.UG,a),500);a.Y.T(h,"mouseover",
a.HD);a.Y.T(h,"mouseout",a.GD,_.t,a);g&&_.la.setTimeout((0,_.H)(function(){this.fa||this.Y.T(window.document,"click",this.CE)},a),0)};
var Jl=function(a,b,c,d){var f=(0,_.cl)(a),g=(0,_.Tk)(f.offsetParent);g.right-=a.og;g.bottom-=a.sg;if(d){var h=f.offsetLeft;d=h+b<g.right;h=h+f.offsetWidth-b>=g.left;a.Da=a.Da?!d||h:!d&&h;h=f.offsetTop;d=h+c<g.bottom;h=h+f.offsetHeight-c>=g.top;a.ua=a.ua?!d||h:!d&&h}d=Kl(a,a.Da,f.offsetLeft,f.offsetWidth,b,g.left,g.right);a=Kl(a,a.ua,f.offsetTop,f.offsetHeight,c,g.top,g.bottom);return new Fl(b,c,d,a,1)};
var Kl=function(a,b,c,d,f,g,h){return b?(a=c+d,Math.min(h-a,Math.max(g+f-a,0))):Math.max(g-c,Math.min(h-c-f,0))};var Ll=function(a,b,c){a.N.Fa().style.width=b+"px";a.N.Fa().style.height=c+"px";a.Q.style.width=b+"px";a.Q.style.height=c+"px";b=a.ig?Jl(a,b,c,_.t):Gl(a.lb,b,c);a.C=b;a.G||Ml(a,b)};
_.Nl=function(a,b){Ol(a,Gl(b,_.l,0,0));_.la.setTimeout((0,_.H)(function(){this.G||(this.C=b,this.Cc&&(0,_.Cl)(this.B,"width 350ms cubic-bezier(.23, .50, .32, 1),height 350ms cubic-bezier(.23, .50, .32, 1),left 350ms cubic-bezier(.23, .50, .32, 1),top 350ms cubic-bezier(.23, .50, .32, 1),opacity 350ms cubic-bezier(.23, .50, .32, 1)"),Ml(this,b),this.Aj(_.n,_.t),this.na&&(_.la.clearTimeout(this.na),this.cb=_.t),this.na=_.la.setTimeout((0,_.H)(this.Aj,this,_.n,_.n),350))},a),0)};
var Pl=function(a){a.G||(a.Aj(_.t,_.t),Ml(a,Gl(a.lb,_.l,0,0)),a.G=_.n,a.na&&_.la.clearTimeout(a.na),a.na=_.la.setTimeout((0,_.H)(function(){this.Db=_.n;this.cb?(Ql(this),this.cb=_.t):(this.Cc&&(0,_.Cl)(this.B,""),this.B.visibility="hidden",this.B.left="-1000px",this.B.top="-1000px");this.Aj(_.t,_.n)},a),350))};var Ql=function(a){a.fa=_.n;(0,_.si)(a.Y);a.Y=_.p;a.J&&(_.la.clearTimeout(a.J),a.J=_.p);a.W&&(_.la.clearTimeout(a.W),a.W=_.p);(0,_.Mi)(a.B);a.B=_.p;(0,_.Mi)((0,_.cl)(a));a.Q=_.p;a.D=_.p};
var Ml=function(a,b){if(!a.G)if(a.Cc)Ol(a,b);else{var c=(0,_.Ka)()-20+350;a.W&&_.la.clearTimeout(a.W);a.dv(a.lb,b,c)}};var Ol=function(a,b){var c=a.B,d=(0,_.cl)(a);c.style.left=a.Da?d.offsetLeft+d.offsetWidth+b.A-b.width+"px":d.offsetLeft+b.A+"px";c.style.width=b.width+"px";c.style.top=a.ua?d.offsetTop+d.offsetHeight+b.B-b.height+"px":d.offsetTop+b.B+"px";c.style.height=b.height+"px";(0,_.Kk)(c,b.opacity);a.lb=b};
Fl.prototype.pe=function(a){return this.width==a.width&&this.height==a.height&&this.A==a.A&&this.B==a.B&&this.opacity==a.opacity};(0,_.I)(_.Hl,_.bl);_.Hl.prototype.open=function(){(0,_.Il)(this);this.N.Gd(this.B);this.N.Qa("resize",(0,_.H)(this.xc,this));this.N.Fb("showMenu",(0,_.H)(this.Rw,this));var a=this.N.xb;a.setHideOnLeave=(0,_.H)(this.Du,this);a.displayStateCallback&&(this.Md=a.displayStateCallback,delete a.displayStateCallback);this.N.Ic(this.Q,{height:"100%"});(0,_.Nl)(this,this.C)};_.Hl.prototype.open=_.Hl.prototype.open;
_.Hl.prototype.Jb=function(a){this.fa||(a=a||{},this.Q.style.left="0",this.Q.style.top="0",this.D&&((0,_.Mi)(this.D),this.D=_.p),this.gc&&(_.la.clearTimeout(this.gc),this.gc=_.p),Ll(this,(0,window.parseInt)(a.width,10)||(0,window.parseInt)(this.N.width,10)||this.C.width,(0,window.parseInt)(a.height,10)||(0,window.parseInt)(this.N.height,10)||this.C.height))};_.Hl.prototype.onready=_.Hl.prototype.Jb;
_.Hl.prototype.xc=function(a){this.fa||Ll(this,(0,window.isNaN)(+a.width)?this.C.width:+a.width,(0,window.isNaN)(+a.height)?this.C.height:+a.height)};_.Hl.prototype.close=function(){this.Db?Ql(this):(this.cb=_.n,Pl(this))};_.Hl.prototype.close=_.Hl.prototype.close;_.F=_.Hl.prototype;_.F.Qe=function(a,b){for(var c,d=1,f=arguments.length;d<f&&(c=this.A[arguments[d]],c===_.l);++d);return c!==_.l?c&&"object"==typeof c?(d={},(0,_.hk)(d,c),d):c:a};_.F.Du=function(a){this.Le=!!a};
_.F.HD=function(){!this.G&&this.J&&(_.la.clearTimeout(this.J),this.J=_.p)};_.F.GD=function(a){if(!(this.G||this.J||!this.Le||a.relatedTarget&&(0,_.Qi)(this.B,a.relatedTarget))){var b=(0,_.Sk)(this.B);a=a.clientY>b.top&&a.clientY<b.top+b.height?0:300;this.J=_.la.setTimeout((0,_.H)(this.zo,this),a)}};_.F.CE=function(a){(0,_.fl)(this.B,a)||this.zo()};_.F.Rw=function(a){this.show(a||a===_.l)};_.F.show=function(a){a?!this.fa&&this.Db&&(this.G=this.Db=_.t,(0,_.Nl)(this,this.C)):this.zo()};
_.F.zo=function(){this.G||Pl(this)};_.F.Aj=function(a,b){var c=this.Md;c&&_.la.setTimeout(function(){c(a,b)},0)};_.F.UG=function(){this.D=window.document.createElement("div");this.D.style.width=this.D.style.height="100%";this.D.style.position="absolute";this.D.style.background="url(//ssl.gstatic.com/ui/v1/activityindicator/loading_gs.gif) no-repeat "+(this.C.width-19)/2+"px "+(this.C.height-19)/2+"px";this.B.appendChild(this.D)};
_.F.dv=function(a,b,c){this.W=_.p;if(!this.fa&&!a.pe(b)){var d=(0,_.Ka)();if(d>=c)Ol(this,b);else{var d=Math.min(1-(c-d)/350,1),d=1-Math.pow(1-d,3),f=1-d,d=new Fl(Math.round(a.width*f+b.width*d),Math.round(a.height*f+b.height*d),Math.round(a.A*f+b.A*d),Math.round(a.B*f+b.B*d),a.opacity*f+b.opacity*d);Ol(this,d);this.W=_.la.setTimeout((0,_.H)(this.dv,this,a,b,c),20)}}};

_.V.Za("slide-menu",function(a){return new _.ll(new _.Hl(a))});
});

// Copyright 2002-2013 Google Inc.
